/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ALIAS_BASE 		0x22000000U
#define BITBAND_BASE 	0x20000000U

int main(void)
{

	// Calculate th bit band alias address for given band memory address and bit position
	//7th bit position of the memory location 0x2000_0200 using its alias address
	// clear bit 7: 1 => 0

	// Alias address = alias_base + (32* (bit_band_memory_addr - bit_band_base)) + bit *4
	// Alias_base address 		= 0x2200_0000
	// Bit_band_base address 	= 0x2000_0000
	// Bit_band_memory_addr 	= 0x2000_0200


	uint8_t *ptr = (uint8_t*)0x20000200;

	// Set all bits to 1 in the address
	*ptr = 0xff;

	// Normal method: clear bit 7 of this address
	*ptr &= ~( 1 << 7);

	// Set all bits to 1 in the address
	*ptr = 0xff;

	//Bit band method
	uint8_t* alias_addr = (uint8_t*) (ALIAS_BASE + (32 * (0x20000200 - BITBAND_BASE)) + 7 * 4);
	// Clearing 7th bit of address 0x2000_0200
	*alias_addr = 0;



    /* Loop forever */
	for(;;);
}
