/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR				0x40023800UL  	// From reference manual 2.3 Memory Map RC
#define RCC_CFRG__REG_OFFSET		0x08            // From reference manual 7.3.3 RCC clock configuration register (RC_CFGR) to
													// set MCO1 Microcontroller clock output 1 bits22:21 to 00 (HSI clock selcted)
#define RCC_CFRG_REG_ADDR			(RCC_BASE_ADDR  + RCC_CFRG__REG_OFFSET)

#define GPIOA_BASE_ADDR            	0x40020000UL

int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFRG_REG_ADDR;		// Pointer to address of RCC clock configuration register (RCC_CFGR)


	// 1. Configure the RCC_CFRG register to select HSI as clock source
	*pRccCfgrReg &= ~(0x03 << 21);              // Bit shift 21 places, AND with value 11 (= hex 0x03) (with bit 22 and bit 21), invert (~)

	//Configure MCO1 prescaler, bit 26,25,25 => 110 => division by 4
	*pRccCfgrReg |= ( 1 << 25);
	*pRccCfgrReg |= ( 1 << 26);

	// 2. Configure PA8 to AF0 mode to behave as MCO1 signal

	// Enable the peripheral clock for GPIOA peripheral

	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= ( 1 << 0); //Enable GPIOA peripheral clock => RCC AHB1 peripheral clock enable register (RCC_AHB1ENR) => first bit is GPIOA

	// Configure the mode of GPIOA pin 8 as alternate function mode

	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //set

	// Configure the alternation function register to set the mode 0 for PA8

	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);


	for(;;);
}
