/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include"main.h"


void task1_handler(void);   // This is task 1
void task2_handler(void);   // This is task 2
void task3_handler(void);   // This is task 3
void task4_handler(void);   // This is task 4

__attribute__((naked)) void init_schedular_stack(uint32_t sched_top_of_stack);
void enable_Processor_faults(void);
void init_tasks_stack(void);
void init_systick_timer(uint32_t tick_hz);
void switch_sp_to_psp(void);
void save_psp_value(uint32_t current_psp_value);
void update_next_task(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);

uint32_t psp_of_tasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];
uint8_t current_task = 0;  // init global variable current task =. task 1 is running




int main(void)
{
	enable_Processor_faults();

	init_schedular_stack(SCHED_STACK_START);

	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;

	init_tasks_stack();
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	/* Loop forever */
	for(;;);
}


void task1_handler(void)
{
	while(1)
	{
		printf("This is task 1\n");
	}
}
void task2_handler(void)
{
	while(1)
	{
		printf("This is task 2\n");
	}
}
void task3_handler(void)
{
	while(1)
	{
		printf("This is task 3\n");
	}
}
void task4_handler(void)
{
	while(1)
	{
		printf("This is task 4\n");
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;				// Systick Reload Value Register
	uint32_t *pSCSR = (uint32_t*)0xE000E010;				// Systick Controle and Status Register
	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz)-1;
	// Clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	// Load the value into SVR
	*pSRVR |= count_value;

	// do some settings
	*pSCSR |= ( 1 << 1 );									// Enables Systick exeption request
	*pSCSR |= ( 1 << 2 );									// Sets the clock source => processor clock source

	// enable the systick
	*pSCSR |= ( 1 << 0 );									// Enables the counter


}

__attribute__((naked)) void init_schedular_stack(uint32_t sched_top_of_stack)
{
	__asm volatile("MSR MSP,%0": : "r"  (sched_top_of_stack) : );
	__asm volatile("BX LR");
}



void init_tasks_stack(void)
{
	uint32_t *pPSP;
	for(int i = 0;i < MAX_TASKS;i++)
	{
		//   dummy stack aanmaken voor elke taak.
		pPSP = (uint32_t*) psp_of_tasks[i];
		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x01000000
		pPSP--;
		*pPSP = task_handlers[i];  // PC (pointer to start address task
		pPSP--;
		*pPSP = 0xFFFFFFFD;       // LR from table of datasheet non float, to PSP
		for(int j=0;j<13;j++)      // 13 registers lege register toevoegen
		{
			pPSP--;
			*pPSP = 0;
		}
		// bewaren psp_of_task
		psp_of_tasks[i] = (uint32_t)pPSP;
	}
}
void enable_Processor_faults(void)
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= ( 1 << 16);  // mem manage
	*pSHCSR |= (1 << 17 );  // bus fault
	*pSHCSR |= (1 << 18 );  // usage fault
}

uint32_t get_psp_value(void)
{
	return psp_of_tasks[current_task];
}

void save_psp_value(uint32_t current_psp_value)
{
	psp_of_tasks[current_task] = current_psp_value;
}

void update_next_task(void)
{
	current_task++;
	current_task %= MAX_TASKS;
}


__attribute__((naked)) void switch_sp_to_psp(void)
{
	// 1. Initialize PSP with TASK1 stack start
	// get the value of sp of current task
	__asm volatile("PUSH {LR}");         // preserve LR which connects back to main()
	__asm volatile("BL get_psp_value");  // branch to and Link back, return value is in r0
	__asm volatile("MSR PSP,R0");        // initialize PSP
	__asm volatile("POP {LR}");          // pops back LR value

	// 2. change SP to PSP using CONTROL register (second bit to 1)
	__asm volatile("MOV R0,#0X02");      // Set value (second bit high) to r0
	__asm volatile("MSR CONTROL,R0");    // r0 => Control register
	__asm volatile("BX LR");             // Goto main()
}

__attribute__((naked)) void SysTick_Handler(void)
{
	/*Save the context of current task */


	//1. Get current running task's PSP value
	__asm volatile("MRS R0,PSP");
	//2. Using that PSP value store SF2 ( R4 to R11)
	__asm volatile("STMDB R0!, {R4-R11}");
	__asm volatile("PUSH {LR}");

	//3. Save the current value of PS
	__asm volatile("BL save_psp_value");

	/*Retrieve the context of next task */
	//1. Decide next task to run
	__asm volatile("BL update_next_task");
	//2. Get its past PSP value
	__asm volatile("BL get_psp_value");
	//3. Using that PSP value to retrieve SF2 (R4 to R11)
	__asm volatile("LDMIA R0!, {R4-R11}");
	//4. Update PSP and exit
	__asm volatile("MSR PSP,R0");
	__asm volatile ("POP {LR}" );
	__asm volatile("BX LR");             // Goto main()
}


// Implementation of fault handlers
void HardFault_Handler(void)
{
	printf("Exeption : Hardfault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exeption : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exeption : Busfault\n");
	while(1);
}

